### ISSUE TITLE
Is it possible to provide Unity scenes with 3D models?

### ISSUE THREAD

**Issue by HusterHope** [Unity-Technologies/SyntheticHomes#2]
Many thanks to your team for providing a high-quality dataset.
We would like to explore this kind of dataset in a virtual reality environment. The current database is mainly for computer vision tasks. Is it possible to provide Unity scenes containing 3D models?

**Comment by tomhog** [comment]
Releasing the project would also be amazing.
I have edge cases it would be nice to make scenes for.

Thanks

**Comment by mkamalza** [comment]
Thank you for posting @HusterHope and @tomhog. Unfortunately, there are currently no plans to release the source project or allow injection of custom models or scenes.
